### ISSUE TITLE
Using tabs for indentation results in a parsing error

### ISSUE THREAD

**Issue by Suseika** [teamed/est#10]
An example file (Github replaces tabs with spaces, unfortunately):

	date: 02-06-2015
	author: Georgy Vlasov
	method: champions.pert
	scope:
		1: test
	champions:
		1: 
			worst-case: 10
			best-case: 5
			most-likely: 7

Error log when I try to run `est` on it (`estimate.est`):

	$ est
	/usr/lib/ruby/2.1.0/psych.rb:370:in `parse': (/path/estimate.est): found character that cannot start any token while scanning for the next token at line 5 column 1 (Psych::SyntaxError)
			from /usr/lib/ruby/2.1.0/psych.rb:370:in `parse_stream'
			from /usr/lib/ruby/2.1.0/psych.rb:318:in `parse'
			from /usr/lib/ruby/2.1.0/psych.rb:245:in `load'
			from /usr/lib/ruby/2.1.0/psych.rb:464:in `block in load_file'
			from /usr/lib/ruby/2.1.0/psych.rb:464:in `open'
			from /usr/lib/ruby/2.1.0/psych.rb:464:in `load_file'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimate.rb:39:in `initialize'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimates.rb:65:in `new'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimates.rb:65:in `block in iterate'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimates.rb:65:in `map'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimates.rb:65:in `iterate'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est/estimates.rb:81:in `initialize'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est.rb:73:in `new'
			from /var/lib/gems/2.1.0/gems/est-0.3/lib/est.rb:73:in `xml'
			from /var/lib/gems/2.1.0/gems/est-0.3/bin/est:76:in `<top (required)>'
			from /usr/local/bin/est:23:in `load'
			from /usr/local/bin/est:23:in `<main>'

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@Suseika I think it's by design. It's YAML format and TAB characters are not allowed there
