### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ZaidPathan** [teamed/est#11]
While installing it this, I got this error:

`ZAIDs-MBP:~ zaidpathan$ gem install est`
`ERROR:  While executing gem ... (Gem::FilePermissionError)`
`    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`

How can I fix this?

**Comment by yegor256** [comment]
@ZaidPathan it's a system Ruby-related problem, this may help: http://stackoverflow.com/questions/17550903/why-do-i-get-a-permission-denied-error-while-installing-a-gem
