### ISSUE TITLE
Estimates should have only coding time

### ISSUE THREAD

**Issue by dalifreire** [teamed/est#13]
As described [here](https://github.com/teamed/est/blob/master/README.md):
Estimate code writing time only. Don't estimate time you would spend on discussions, thinking, modeling, diagramming, documenting etc.

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@dalifreire what exactly do you want us to change in the source code of this tool?

**Comment by dalifreire** [comment]
@yegor256 I'm talking about the [estimative file](https://github.com/teamed/est/blob/master/est/first.est). User documentation should not be part of the estimation as explained [here](https://github.com/teamed/est/blob/master/README.md). This maybe cause some confusion when other people need create estimates to other projects and use this project as an sample ([like me did](https://github.com/yegor256/rultor/pull/1030)).

**Comment by davvd** [comment]
@dalifreire many thanks for the bug report, I added 15 mins to your acc, transaction `79406625`

**Comment by ekondrashev** [comment]
@dalifreire could you please elaborate why user doc should not be included? If it considers changing codebase - it is a technical effort imho.

**Comment by dalifreire** [comment]
@ekondrashev Just read the [est](https://github.com/teamed/est) project documentation. Pay attention at the **Best Practices** section of the [README](https://github.com/teamed/est/blob/master/README.md).

**Comment by ekondrashev** [comment]
@dalifreire ok, maybe it is wrong place to ask, I was looking for the original motivation answer, but not the reference. Anyway there is a defect asking this also. See #14 if interested.

**Comment by yegor256** [comment]
@dalifreire fixed in  b5e8fe5 thanks!
