### ISSUE TITLE
The description of a project and a sample differs from what patent says

### ISSUE THREAD

**Issue by ekondrashev** [teamed/est#14]
The `Readme.md` provides a sample and the description that causes controversy comparing to what [article](http://www.technoparkcorp.com/innovations/scope-champions/)/[patent](http://www.google.com/patents/US20100042968) states.

In particular, patent states that it is functional requirements that should go into separate line only. While the sample for the `est` project contains covering functionality with unit test as a line(champion candidate). This causes a lot of confusion, like happened [here](https://github.com/teamed/xockets-xjm/pull/622#issuecomment-204706109)

Secondly, the description itself is pretty poor comparing to patent/article. It states:
```
First, you break down the entire implementation scope into items, like it's done above, and list them under scope. 
Pay attention, you should list only technical code-writing tasks. 
```
emphasising to break down the project into technical code-writing tasks but not a functional requirement like patent states, forcing reviewers to deny estimates like this:
```
  1: Document the workflow/user stories
  2: Document each communicating component
  3: Implement X abstraction layer
  4: Cover X abstraction layer with tests
  5: Implement REST endpoints
  6: Cover REST endpoints with tests
  7: Implement Y abstraction layer
  8: Cover Y abstraction layer with tests
  9: Implement Z abstraction layer
  10: Cover Z abstraction layer with test
  11: Implement basic HTML Web UI
  12: Cover basic HTML Web UI with tests
  13: Implement command line interface tying all components together
  14: Introduce bunch of integration tests fixing level 0 issues
  15: Implement extended HTML Web UI introducing dynamics
  16: Cover extended HTML Web UI with tests
  17: Fixing defects
```

Lets fix the readme file, so it will not cause confusions no more.

IMHO
I find it pretty handy to have a possibility to put unit/integration tests, documentations and feature implementation in separate line(champion candidates), since it increases granularity giving a possibility to break down the project scope into really comparable by size items - hence increase the accuracy, which is the final goal in the end.

From the other hand, if line would only contain requirements, it increases the risk of having pretty different in size champion candidates. Let me elaborate. Each requirement implementation contains of following parts which considered to be technical code writing tasks since causes code base change -> and are payed in the end:
* technical specification - this is description of input/output parameters if we talk about REST endpoint or creation of HTML mockups if we talk about Web UI feature
* feature implementation
* test coverage, unit + integration
* fixing defects

I'd also add user doc in this list, since it leads to code base change also. Keeping in mind all those parts, it makes the item pretty heavy, forcing the performer to split the requirement into sub requirements if its size is pretty big comparing to other lines. Often this split is artificial and redundant, since performer is not that deep dived into details of a requirement exceeding the limit of a budget for the estimation.

From the other hand, if one wouldn't be limited to put only requirement into the line it will make the process of estimation much more simple.

**Comment by ekondrashev** [comment]
@yegor256 Could you please take a look. This issue caused a lot of discussions recently

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@ekondrashev I removed tests from the example: b5e8fe5 thanks!
