### ISSUE TITLE
Failed to install dependency on Ubuntu 16.04

### ISSUE THREAD

**Issue by amihaiemil** [teamed/est#15]
When I first ran ``gem install est`` all went fine until it had to install ``ruby-filemagic``. Turns out the lib was missing some header files and fixed the issue by running: 

``sudo apt-get install libmagic-dev``

After that, the installation worked fine. 
Maybe this can be specified in the README file under an "Installation troubleshootings"?

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@amihaiemil check this out: 515b86a hope it helps, thanks!
