### ISSUE TITLE
README doesn't give recommendations for re-estimate process

### ISSUE THREAD

**Issue by alevohin** [teamed/est#5]
README doesn't give recommendations for re-estimate process. For example
- Is it better to use previous estimate or remake estimate?
- Is it better to use one person to re-estimate during project lifetime one new one?

**Comment by davvd** [comment]
I will find a developer for the task soon...

**Comment by davvd** [comment]
@alevohin thank you for the ticket reported, I topped your account for 15 mins, transaction `52975279`

**Comment by yegor256** [comment]
@alevohin check fb85472 good enough?

**Comment by alevohin** [comment]
@yegor256 yes, great! thank you!
